Restarted .venv (Python 3.10.16)

In [1]:
import os, sys
import pandas as pd

In [2]:
os.getcwd()
os.chdir('..')
os.getcwd()

'/Users/nkapila6/Code/nlpvise/src'

In [3]:
mimic3_path = 'data/'

In [4]:
print('\nStep 8.1: Loading data to merge.')
if os.path.exists(os.path.join(mimic3_path, 'multiclass_diag_target.pkl')):
    diag = pd.read_pickle(f'{os.path.join(mimic3_path, "multiclass_diag_target.pkl")}')
    notes = pd.read_pickle(f'{os.path.join(mimic3_path, "notes_with_embeddings.pkl")}')
    print('Data loaded.')

Step 8.1: Loading data to merge.
Data loaded.

In [5]:
df = pd.DataFrame({
    'EMBEDDING': notes['EMBEDDING'],
    'SUBJECT_ID': notes['SUBJECT_ID']
})

In [6]:
df

                                                EMBEDDING  SUBJECT_ID
0       [-0.036008064, -0.057632454, -0.5764836, 0.473...       31608
1       [0.04741407, -0.25133044, -0.42309144, 0.49156...       31608
2       [0.054948103, 0.30195963, -0.5842947, 0.443203...       31608
3       [0.14360966, -0.1609861, -0.49888694, 0.472669...       31608
4       [0.14360966, -0.1609861, -0.49888694, 0.472669...       31608
...                                                   ...         ...
142105  [-0.015362617, 0.06871149, -0.9058058, 0.60461...       40191
142106  [0.044867028, 0.11367364, -0.49641666, 0.56927...       85259
142107  [0.0155562265, 0.24602246, -0.39466158, 0.6142...       85259
142108  [0.070035756, -0.014688486, -0.46918246, 0.556...       85259
142109  [0.060214076, 0.035432372, -0.64930576, 0.4715...       85259

[142110 rows x 2 columns]

In [7]:
diag.columns

Index(['SUBJECT_ID', 'TARGETS'], dtype='object')

In [8]:
data = pd.merge(df, diag, on='SUBJECT_ID', how='inner')

In [9]:
data

,EMBEDDING,SUBJECT_ID,TARGETS
0,"[-0.036008064, -0.057632454, -0.5764836, 0.473...",31608,"[8, 7, 2, 4, 15, 19]"
1,"[0.04741407, -0.25133044, -0.42309144, 0.49156...",31608,"[8, 7, 2, 4, 15, 19]"
2,"[0.054948103, 0.30195963, -0.5842947, 0.443203...",31608,"[8, 7, 2, 4, 15, 19]"
3,"[0.14360966, -0.1609861, -0.49888694, 0.472669...",31608,"[8, 7, 2, 4, 15, 19]"
4,"[0.14360966, -0.1609861, -0.49888694, 0.472669...",31608,"[8, 7, 2, 4, 15, 19]"
...,...,...,...
142105,"[-0.015362617, 0.06871149, -0.9058058, 0.60461...",40191,"[3, 15, 19, 5, 2, 16, 7, 9, 10, 4]"
142106,"[0.044867028, 0.11367364, -0.49641666, 0.56927...",85259,"[7, 8, 10, 19]"
142107,"[0.0155562265, 0.24602246, -0.39466158, 0.6142...",85259,"[7, 8, 10, 19]"
142108,"[0.070035756, -0.014688486, -0.46918246, 0.556...",85259,"[7, 8, 10, 19]"
142109,"[0.060214076, 0.035432372, -0.64930576, 0.4715...",85259,"[7, 8, 10, 19]"

In [10]:
data.shape

(142110, 3)

In [11]:
data.isna().sum()

EMBEDDING     0
SUBJECT_ID    0
TARGETS       0
dtype: int64

In [12]:
data.to_pickle('data/dataset_df.pkl')

In [13]:
import data as step

In [14]:
import numpy as np

In [ ]:
y = np.stack(data['TARGETS'].apply(step.y_mhe))

In [16]:
y

array([[0, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=uint64)

In [17]:
data['EMBEDDING']

0         [-0.036008064, -0.057632454, -0.5764836, 0.473...
1         [0.04741407, -0.25133044, -0.42309144, 0.49156...
2         [0.054948103, 0.30195963, -0.5842947, 0.443203...
3         [0.14360966, -0.1609861, -0.49888694, 0.472669...
4         [0.14360966, -0.1609861, -0.49888694, 0.472669...
                                ...
142105    [-0.015362617, 0.06871149, -0.9058058, 0.60461...
142106    [0.044867028, 0.11367364, -0.49641666, 0.56927...
142107    [0.0155562265, 0.24602246, -0.39466158, 0.6142...
142108    [0.070035756, -0.014688486, -0.46918246, 0.556...
142109    [0.060214076, 0.035432372, -0.64930576, 0.4715...
Name: EMBEDDING, Length: 142110, dtype: object

In [18]:
X = np.stack(data['EMBEDDING'])

In [19]:
X

array([[-0.03600806, -0.05763245, -0.5764836 , ...,  0.05967164,
        -0.06377713, -0.15175182],
       [ 0.04741407, -0.25133044, -0.42309144, ...,  0.02087078,
         0.12380733, -0.0428645 ],
       [ 0.0549481 ,  0.30195963, -0.5842947 , ..., -0.05654861,
         0.12264945, -0.35312414],
       ...,
       [ 0.01555623,  0.24602246, -0.39466158, ..., -0.06074153,
        -0.00849961, -0.11809866],
       [ 0.07003576, -0.01468849, -0.46918246, ...,  0.03723217,
         0.13071527, -0.04235954],
       [ 0.06021408,  0.03543237, -0.64930576, ...,  0.24909644,
         0.01986872, -0.04088048]], dtype=float32)

In [25]:
import pickle

print('\nSaving X and y for dataset.')
with open("data/X.pkl", "wb") as f:
    pickle.dump(X, f)

with open("data/y.pkl", "wb") as f:
    pickle.dump(y, f)

Saving X and y for dataset.

In [21]:
X

array([[-0.03600806, -0.05763245, -0.5764836 , ...,  0.05967164,
        -0.06377713, -0.15175182],
       [ 0.04741407, -0.25133044, -0.42309144, ...,  0.02087078,
         0.12380733, -0.0428645 ],
       [ 0.0549481 ,  0.30195963, -0.5842947 , ..., -0.05654861,
         0.12264945, -0.35312414],
       ...,
       [ 0.01555623,  0.24602246, -0.39466158, ..., -0.06074153,
        -0.00849961, -0.11809866],
       [ 0.07003576, -0.01468849, -0.46918246, ...,  0.03723217,
         0.13071527, -0.04235954],
       [ 0.06021408,  0.03543237, -0.64930576, ...,  0.24909644,
         0.01986872, -0.04088048]], dtype=float32)

In [26]:
with open("data/X.pkl", "rb") as f:
        X2 = pickle.load(f)

In [27]:
X2

array([[-0.03600806, -0.05763245, -0.5764836 , ...,  0.05967164,
        -0.06377713, -0.15175182],
       [ 0.04741407, -0.25133044, -0.42309144, ...,  0.02087078,
         0.12380733, -0.0428645 ],
       [ 0.0549481 ,  0.30195963, -0.5842947 , ..., -0.05654861,
         0.12264945, -0.35312414],
       ...,
       [ 0.01555623,  0.24602246, -0.39466158, ..., -0.06074153,
        -0.00849961, -0.11809866],
       [ 0.07003576, -0.01468849, -0.46918246, ...,  0.03723217,
         0.13071527, -0.04235954],
       [ 0.06021408,  0.03543237, -0.64930576, ...,  0.24909644,
         0.01986872, -0.04088048]], dtype=float32)