Restarted .venv (Python 3.10.16)

In [1]:
import os, sys
import pandas as pd

In [2]:
os.getcwd()
os.chdir('../..')
os.getcwd()

'/Users/nkapila6/Code/nlpvise/src'

In [3]:
mimic3_path = 'data/'

In [4]:
print('\nStep 8.1: Loading data to merge.')
if os.path.exists(os.path.join(mimic3_path, 'multiclass_diag_target.pkl')):
    diag = pd.read_pickle(f'{os.path.join(mimic3_path, "multiclass_diag_target.pkl")}')
    notes = pd.read_pickle(f'{os.path.join(mimic3_path, "notes_with_embeddings_MEAN.pkl")}')
    print('Data loaded.')

Step 8.1: Loading data to merge.
Data loaded.

In [5]:
df = pd.DataFrame({
    'EMBEDDING': notes['EMBEDDING'],
    'SUBJECT_ID': notes['SUBJECT_ID']
})

In [6]:
df

                                                EMBEDDING  SUBJECT_ID
0       [0.20631364, -0.44404224, -0.12459257, 0.24738...       31608
1       [0.23262683, -0.6760833, -0.057412244, 0.35846...       31608
2       [0.19450292, -0.12628329, -0.28447592, 0.27614...       31608
3       [0.15812537, -0.5567824, -0.12215112, 0.418693...       31608
4       [0.15812537, -0.5567824, -0.12215112, 0.418693...       31608
...                                                   ...         ...
142105  [0.11719368, -0.27339247, -0.33821213, 0.20962...       40191
142106  [0.25609925, -0.2533742, -0.19354494, 0.187750...       85259
142107  [0.19077775, -0.15893398, -0.016997622, 0.3450...       85259
142108  [0.25270894, -0.41641697, -0.10034665, 0.23003...       85259
142109  [0.19960865, -0.33914346, -0.23394534, 0.18901...       85259

[142110 rows x 2 columns]

In [7]:
diag.columns

Index(['SUBJECT_ID', 'TARGETS'], dtype='object')

In [8]:
data = pd.merge(df, diag, on='SUBJECT_ID', how='inner')

In [9]:
data

,EMBEDDING,SUBJECT_ID,TARGETS
0,"[0.20631364, -0.44404224, -0.12459257, 0.24738...",31608,"[8, 7, 2, 4, 15, 19]"
1,"[0.23262683, -0.6760833, -0.057412244, 0.35846...",31608,"[8, 7, 2, 4, 15, 19]"
2,"[0.19450292, -0.12628329, -0.28447592, 0.27614...",31608,"[8, 7, 2, 4, 15, 19]"
3,"[0.15812537, -0.5567824, -0.12215112, 0.418693...",31608,"[8, 7, 2, 4, 15, 19]"
4,"[0.15812537, -0.5567824, -0.12215112, 0.418693...",31608,"[8, 7, 2, 4, 15, 19]"
...,...,...,...
142105,"[0.11719368, -0.27339247, -0.33821213, 0.20962...",40191,"[3, 15, 19, 5, 2, 16, 7, 9, 10, 4]"
142106,"[0.25609925, -0.2533742, -0.19354494, 0.187750...",85259,"[7, 8, 10, 19]"
142107,"[0.19077775, -0.15893398, -0.016997622, 0.3450...",85259,"[7, 8, 10, 19]"
142108,"[0.25270894, -0.41641697, -0.10034665, 0.23003...",85259,"[7, 8, 10, 19]"
142109,"[0.19960865, -0.33914346, -0.23394534, 0.18901...",85259,"[7, 8, 10, 19]"

In [10]:
data.shape

(142110, 3)

In [11]:
data.isna().sum()

EMBEDDING     0
SUBJECT_ID    0
TARGETS       0
dtype: int64

In [12]:
data.to_pickle('data/dataset_df_MEAN.pkl')

In [13]:
import data as step

In [14]:
import numpy as np

In [15]:
y = np.stack(data['TARGETS'].apply(step.y_mhe))

In [16]:
y

array([[0, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=uint64)

In [17]:
data['EMBEDDING']

0         [0.20631364, -0.44404224, -0.12459257, 0.24738...
1         [0.23262683, -0.6760833, -0.057412244, 0.35846...
2         [0.19450292, -0.12628329, -0.28447592, 0.27614...
3         [0.15812537, -0.5567824, -0.12215112, 0.418693...
4         [0.15812537, -0.5567824, -0.12215112, 0.418693...
                                ...
142105    [0.11719368, -0.27339247, -0.33821213, 0.20962...
142106    [0.25609925, -0.2533742, -0.19354494, 0.187750...
142107    [0.19077775, -0.15893398, -0.016997622, 0.3450...
142108    [0.25270894, -0.41641697, -0.10034665, 0.23003...
142109    [0.19960865, -0.33914346, -0.23394534, 0.18901...
Name: EMBEDDING, Length: 142110, dtype: object

In [18]:
X = np.stack(data['EMBEDDING'])

In [19]:
X

array([[ 0.20631364, -0.44404224, -0.12459257, ...,  0.07726249,
        -0.28615013, -0.00592945],
       [ 0.23262683, -0.6760833 , -0.05741224, ...,  0.05930402,
        -0.17492321,  0.05269586],
       [ 0.19450292, -0.12628329, -0.28447592, ...,  0.08679035,
        -0.27400795, -0.21470568],
       ...,
       [ 0.19077775, -0.15893398, -0.01699762, ...,  0.2521493 ,
        -0.19124061, -0.01828537],
       [ 0.25270894, -0.41641697, -0.10034665, ...,  0.14024025,
        -0.1844983 ,  0.10219409],
       [ 0.19960865, -0.33914346, -0.23394534, ...,  0.18734786,
        -0.26054907,  0.10926247]], dtype=float32)

In [20]:
import pickle

print('\nSaving X and y for dataset.')
with open("data/X_MEAN.pkl", "wb") as f:
    pickle.dump(X, f)

with open("data/y_MEAN.pkl", "wb") as f:
    pickle.dump(y, f)

Saving X and y for dataset.

In [21]:
X

array([[ 0.20631364, -0.44404224, -0.12459257, ...,  0.07726249,
        -0.28615013, -0.00592945],
       [ 0.23262683, -0.6760833 , -0.05741224, ...,  0.05930402,
        -0.17492321,  0.05269586],
       [ 0.19450292, -0.12628329, -0.28447592, ...,  0.08679035,
        -0.27400795, -0.21470568],
       ...,
       [ 0.19077775, -0.15893398, -0.01699762, ...,  0.2521493 ,
        -0.19124061, -0.01828537],
       [ 0.25270894, -0.41641697, -0.10034665, ...,  0.14024025,
        -0.1844983 ,  0.10219409],
       [ 0.19960865, -0.33914346, -0.23394534, ...,  0.18734786,
        -0.26054907,  0.10926247]], dtype=float32)

In [22]:
with open("data/X_MEAN.pkl", "rb") as f:
        X2 = pickle.load(f)

In [23]:
X2

array([[ 0.20631364, -0.44404224, -0.12459257, ...,  0.07726249,
        -0.28615013, -0.00592945],
       [ 0.23262683, -0.6760833 , -0.05741224, ...,  0.05930402,
        -0.17492321,  0.05269586],
       [ 0.19450292, -0.12628329, -0.28447592, ...,  0.08679035,
        -0.27400795, -0.21470568],
       ...,
       [ 0.19077775, -0.15893398, -0.01699762, ...,  0.2521493 ,
        -0.19124061, -0.01828537],
       [ 0.25270894, -0.41641697, -0.10034665, ...,  0.14024025,
        -0.1844983 ,  0.10219409],
       [ 0.19960865, -0.33914346, -0.23394534, ...,  0.18734786,
        -0.26054907,  0.10926247]], dtype=float32)

In [25]:
np.array_equal(X,X2)

True